#include "std_include.hpp"
#include "comp_settings.hpp"
#include "shared/common/toml_ext.hpp"

#define CATCH_ERR_PRINT	catch (toml::type_error& err) { \
		shared::common::log("CompSettings", std::format("{}", err.what()), shared::common::LOG_TYPE::LOG_TYPE_ERROR, true); }

namespace gta4
{
	std::string get_current_comp_version_string()
	{
		return std::string(std::to_string(COMP_MOD_VERSION_MAJOR) + "." + std::to_string(COMP_MOD_VERSION_MINOR) + "." + std::to_string(COMP_MOD_VERSION_PATCH));
	}

	void comp_settings::write_comp_settings_toml()
	{
		const std::string file_path = shared::globals::root_path + "\\rtx_comp\\comp_settings.toml";
		std::filesystem::create_directories(std::filesystem::path(file_path).parent_path());

		std::ofstream file;
		file.open(file_path.c_str());

		file << "# This file is autogenerated. Valid modifications of settings are considered and will be written back to the file.\n";
		file << "# Installing a new version of the compatibility mod might restore settings whose defaults have changed.\n\n";

		//file << "CreatedOnCompVersion = \"" << get_current_comp_version_string() << "\"\n\n";

		const std::uint32_t setting_count = sizeof(var_definitions) / sizeof(variable);
		for (auto s = 0u; s < setting_count; s++)
		{
			auto var = reinterpret_cast<variable*>(reinterpret_cast<char*>(&vars) + s * sizeof(variable));

			const auto desc_lines = shared::utils::split(std::string(var->m_desc), '\n');
			for (const auto& line : desc_lines) {
				file << "# " + line << std::endl;
			}

			file << "# Type: " << var->get_str_type() << " || Default: " << var->get_str_value(true) << std::endl;
			file << "# Ver: " << var->get_ver_string() << std::endl;
			file << var->m_name << " = " << var->get_str_value() << std::endl << std::endl;
		}

		file.close();
	}

	/// Func used to parse and set comp settings
	/// @param 	is_addon_toml_file	if is addon setting file or not
	/// @param  addon_file_name		not empty = addon parse mode - file name (with ext) of addon file
	/// @return						true if parsed successfully or if defaults were written if no file found, false if parsing failed
	bool comp_settings::parse_toml(std::string addon_file_name)
	{
		// helper
		auto to_vec = [](const toml::value& entry, const var_type type, float* default_vec = nullptr)
			{
				std::vector<float> result;
				const size_t size_for_vec = type == var_type_vec2 ? 2u : type == var_type_vec3 ? 3u : type == var_type_vec4 ? 4u : 0u;

				if (entry.is_array())
				{
					if (entry.as_array().size() == size_for_vec)
					{
						for (const auto& val : entry.as_array())
						{
							if (val.is_floating())
							{
								result.push_back((float)val.as_floating());
								continue;
							}
							TOML_ERROR("[CompSettings] #to_vec", val, "expected float but got value_t of => %d ", val.type());
						}
						return result;
					}
					TOML_ERROR("[CompSettings] #to_vec", entry, "unexpected array size of => %d ", entry.as_array().size());
				}
				TOML_ERROR("[CompSettings] #to_vec", entry, "expected a vector but got value_t => %d ", entry.type());

				switch (type)
				{
				default:
					result = { 0, 0, 0, 0 };
					break;
				case var_type_vec2:
					result = { default_vec[0], default_vec[1] };
					break;
				case var_type_vec3:
					result = { default_vec[0], default_vec[1], default_vec[2] };
					break;
				case var_type_vec4:
					result = { default_vec[0], default_vec[1], default_vec[2], default_vec[3] };
					break;
				}

				return result;
			};


#ifndef asd // DEBUG

		const bool is_addon_toml_file = !addon_file_name.empty();
		if (std::filesystem::exists(!is_addon_toml_file ? "rtx_comp\\comp_settings.toml" : "rtx_comp\\addon_settings\\" + addon_file_name))
		{
			try
			{
				auto config = toml::parse(!is_addon_toml_file ? "rtx_comp\\comp_settings.toml" : "rtx_comp\\addon_settings\\" + addon_file_name);

				// "legacy" format - rewrite on first launch
				if (!is_addon_toml_file && config.contains("CreatedOnCompVersion"))
				{
					write_comp_settings_toml();
					return true;

					/*std::string created_on_comp_version_str;
					auto& val = config.at("CreatedOnCompVersion");
					if (val.is_string())
					{
						try { created_on_comp_version_str = val.as_string(); }
						CATCH_ERR_PRINT;
					}

					if (!created_on_comp_version_str.empty())
					{
						if (created_on_comp_version_str != current_version_str)
						{
							write_comp_settings_toml();
							return true;
						}
					}*/
				}

				const auto current_comp_version = shared::utils::version_t::from_string(get_current_comp_version_string());
				
				//vars.decal_dirt_shader_contrast.set_config_name()
				// ---------------------------------------
				// Used to assign toml settings
				// - check setting version, only read val if setting on disk is older than version the setting was last changed on - use the default val otherwise
				// - guard against invalid version
				// - save users comp_settings value which is later used to write to the file if the user hits save

				#define ASSIGN(name)																															\
					if (config.contains((#name)))																												\
					{																																			\
						std::string setting_last_comment = config.at(#name).comments().back();																	\
						if (setting_last_comment.starts_with("# Ver: "))																						\
						{																																		\
							setting_last_comment.erase(0, 7); const auto s_version = shared::utils::version_t::from_string(setting_last_comment);				\
							if (vars.##name.m_version <= s_version && s_version <= current_comp_version)														\
							{																																	\
								switch (vars.##name.get_type())																									\
								{																																\
								case (var_type_boolean):																										\
										vars.##name.set_var(shared::common::toml_ext::to_bool(config.at(#name), vars.##name.get_as<bool>()), true); break;		\
								case (var_type_integer):																										\
										vars.##name.set_var(shared::common::toml_ext::to_int(config.at(#name), vars.##name.get_as<int>()), true); break;		\
								case (var_type_value):																											\
										vars.##name.set_var(shared::common::toml_ext::to_float(config.at(#name), vars.##name.get_as<float>()), true); break;	\
								case (var_type_vec2):																											\
								case (var_type_vec3):																											\
								case (var_type_vec4):																											\
										const auto vec = to_vec(config.at(#name), vars.##name.get_type(), vars.##name.get_as<float*>());						\
										vars.##name.set_vec(vec.data(), true); break;																			\
								}																																\
								if (!is_addon_toml_file) { vars.##name.set_dirty(false); vars.##name.set_base_user_from_current(); } else { vars.##name.set_dirty(true); } \
							} else { shared::common::log("CompSettings", std::format("Not using saved value for {} because default setting was updated in a recent update.", vars.##name.m_name), shared::common::LOG_TYPE::LOG_TYPE_WARN); } \
						} else { if (is_addon_toml_file) { shared::common::log("CompSettings", std::format("Missing version info for {} - skipping.", vars.##name.m_name), shared::common::LOG_TYPE::LOG_TYPE_WARN); } } \
					}

				

				// remix related settings
				ASSIGN(manual_game_resolution_enabled);
				ASSIGN(manual_game_resolution);
				ASSIGN(load_colormaps_only);
				ASSIGN(remix_override_rtxdi_samplecount);
				ASSIGN(remix_var_queue_frame_timeout);
				
				// culling related settings
				ASSIGN(nocull_dist_near_static);
				ASSIGN(nocull_dist_medium_static);
				ASSIGN(nocull_radius_medium_static);
				ASSIGN(nocull_dist_far_static);
				ASSIGN(nocull_radius_far_static);
				ASSIGN(nocull_height_far_static);
				ASSIGN(nocull_dist_lights);
				ASSIGN(nocull_dist_sphere_interior);

				ASSIGN(nocull_extended);
				ASSIGN(nocull_extended_auto);
				ASSIGN(nocull_extended_dist);
				ASSIGN(nocull_extended_radius);
				ASSIGN(nocull_extended_height);

				ASSIGN(nocull_map_areas);
				ASSIGN(nocull_map_areas_count);
				ASSIGN(nocull_map_areas_always_draw_lowest_lod);
				ASSIGN(nocull_map_areas_always_draw_lowest_lod_min_size);
				ASSIGN(nocull_map_areas_high_lod_logic);
				ASSIGN(nocull_map_areas_high_lod_logic_distance);

				// light translation related settings
				ASSIGN(translate_game_lights);
				ASSIGN(translate_game_lights_ignore_filler_lights);
				ASSIGN(translate_game_lights_no_volumetrics_on_filler_lights);
				ASSIGN(translate_game_light_radius_scalar);
				ASSIGN(translate_game_light_intensity_scalar);
				ASSIGN(translate_game_light_softness_offset);
				ASSIGN(translate_game_light_softness_scalar);
				ASSIGN(translate_game_light_focus_expo);
				ASSIGN(translate_game_light_spotlight_volumetric_radiance_scale);
				ASSIGN(translate_game_light_spherelight_volumetric_radiance_scale);
				ASSIGN(translate_game_light_angle_offset);

				ASSIGN(translate_sunlight_intensity_scalar);
				ASSIGN(translate_sunlight_intensity_bad_weather_influence);
				ASSIGN(translate_sunlight_angular_diameter_degrees);
				ASSIGN(translate_sunlight_volumetric_radiance_base);
				ASSIGN(translate_sunlight_timecycle_fogdensity_volumetric_influence_enabled);
				ASSIGN(translate_sunlight_timecycle_fogdensity_volumetric_influence_scalar);
				ASSIGN(translate_moonlight_intensity_scalar);

				ASSIGN(translate_vehicle_headlight_intensity_scalar);
				ASSIGN(translate_vehicle_headlight_radius_scalar);
				ASSIGN(translate_vehicle_rearlight_intensity_scalar);
				ASSIGN(translate_vehicle_rearlight_radius_scalar);
				ASSIGN(translate_vehicle_rearlight_inner_cone_angle_offset);
				ASSIGN(translate_vehicle_rearlight_outer_cone_angle_offset);
				ASSIGN(translate_vehicle_rearlight_direction_offset);

				ASSIGN(translate_vehicle_fake_siren_z_offset);
				ASSIGN(translate_vehicle_fake_siren_intensity_offset);
				ASSIGN(translate_vehicle_fake_siren_radius_offset);

				ASSIGN(translate_vehicle_vsirens_make_spotlight);
				ASSIGN(translate_vehicle_vsirens_intensity_offset);
				ASSIGN(translate_vehicle_vsirens_radius_offset);

				ASSIGN(translate_vehicle_vsirens_secondary_spherelight_enabled);
				ASSIGN(translate_vehicle_vsirens_secondary_spherelight_radius_offset);
				ASSIGN(translate_vehicle_vsirens_secondary_spherelight_intensity_offset);
				ASSIGN(translate_vehicle_vsirens_secondary_spherelight_z_offset);
				
				ASSIGN(translate_vehicle_barsirens_intensity_scalar);
				ASSIGN(translate_vehicle_barsirens_radius_scalar);
				
				// emissive related settings
				ASSIGN(vehicle_lights_emissive_scalar);
				ASSIGN(vehicle_lights_dual_render_proxy_texture);
				ASSIGN(emissive_night_surfaces_emissive_scalar);
				ASSIGN(emissive_surfaces_emissive_scalar);
				ASSIGN(emissive_strong_surfaces_emissive_scalar);
				ASSIGN(emissive_generic_scale);
				ASSIGN(emissive_alpha_blend_hack);
				ASSIGN(emissive_alpha_blend_hack_scale);
				ASSIGN(emissive_allow_vertex_colors);
				ASSIGN(phone_emissive_override);
				ASSIGN(phone_emissive_scalar);

				// general rendering related settings
				ASSIGN(vehicle_dirt_enabled);
				ASSIGN(vehicle_dirt_custom_color_enabled);
				ASSIGN(vehicle_dirt_custom_color);

				ASSIGN(vehicle_dirt_expo);
				ASSIGN(vehicle_dirt_roughness_z_normal);
				ASSIGN(vehicle_dirt_roughness_blending);

				ASSIGN(vehicle_livery_enabled);
				ASSIGN(vehicle_force_vertex_colors);

				ASSIGN(decal_dirt_shader_usage);
				ASSIGN(decal_dirt_shader_scalar);
				ASSIGN(decal_dirt_shader_contrast);
				ASSIGN(fixed_function_trees);
				ASSIGN(tree_foliage_alpha_cutout_value);
				ASSIGN(grass_foliage_alpha_cutout_value);
				ASSIGN(npc_expensive_hair_alpha_testing);
				ASSIGN(npc_expensive_hair_alpha_cutout_value);

				ASSIGN(override_water_texture_hash);
				ASSIGN(water_apply_animated_water_category);
				ASSIGN(water_texture_uv_scale);
				ASSIGN(water_texture_normal_fadeout_distance);

				ASSIGN(gta_rmptfx_litsprite_alpha_scalar);
				ASSIGN(rain_particle_system_enabled);

				// timecycle related settings
				//ASSIGN(timecycle_set_on_endscene);
				ASSIGN(timecycle_use_remix_atmos_system);
				ASSIGN(timecycle_wetness_enabled);
				ASSIGN(timecycle_wetness_world_scalar);
				ASSIGN(timecycle_wetness_world_offset);
				ASSIGN(timecycle_wetness_world_z_normal);
				ASSIGN(timecycle_wetness_world_blending);
				ASSIGN(timecycle_wetness_world_variation_enable);
				ASSIGN(timecycle_wetness_world_puddle_layer_enable);
				ASSIGN(timecycle_wetness_world_raindrop_enable);
				ASSIGN(timecycle_wetness_world_raindrop_scalar);
				ASSIGN(timecycle_wetness_world_occlusion_check_enable);
				ASSIGN(timecycle_wetness_world_occlusion_smoothing_enable);

				ASSIGN(timecycle_wetness_ped_raindrop_enable);
				ASSIGN(timecycle_wetness_ped_raindrop_scalar);
				
				ASSIGN(timecycle_wetness_vehicle_scalar);
				ASSIGN(timecycle_wetness_vehicle_z_normal);
				ASSIGN(timecycle_wetness_vehicle_blending);

				ASSIGN(timecycle_wetness_vehicle_raindrop_enable);
				ASSIGN(timecycle_wetness_vehicle_raindrop_scalar);
				
				ASSIGN(timecycle_wetness_vehicle_dirt_intensity_scalar);
				ASSIGN(timecycle_wetness_vehicle_dirt_roughness_scalar);
				ASSIGN(timecycle_wetness_vehicle_dirt_z_normal);
				ASSIGN(timecycle_wetness_vehicle_dirt_blending);

				ASSIGN(timecycle_fogcolor_enabled);
				ASSIGN(timecycle_fogcolor_base_strength);
				ASSIGN(timecycle_fogcolor_influence_scalar);
				ASSIGN(timecycle_fogdensity_enabled);
				ASSIGN(timecycle_fogdensity_influence_scalar);
				ASSIGN(timecycle_skyhorizonheight_enabled);
				ASSIGN(timecycle_skyhorizonheight_scalar);
				ASSIGN(timecycle_skyhorizonheight_low_transmittance_offset);
				ASSIGN(timecycle_skyhorizonheight_high_transmittance_offset);
				ASSIGN(timecycle_skyhorizonheight_cam_height_threshold);
				ASSIGN(timecycle_skyhorizonheight_cam_height_influence_low);
				ASSIGN(timecycle_skyhorizonheight_cam_height_influence_high);
				ASSIGN(timecycle_skylight_enabled);
				ASSIGN(timecycle_skylight_scalar);
				ASSIGN(timecycle_skylight_max_offset_bad_weather);
				ASSIGN(timecycle_colorcorrection_enabled);
				ASSIGN(timecycle_colorcorrection_influence);
				ASSIGN(timecycle_colortemp_enabled);
				ASSIGN(timecycle_colortemp_value);
				ASSIGN(timecycle_colortemp_influence);
				ASSIGN(timecycle_desaturation_enabled);
				ASSIGN(timecycle_desaturation_influence);
				ASSIGN(timecycle_fardesaturation_influence);
				ASSIGN(timecycle_gamma_enabled);
				ASSIGN(timecycle_gamma_offset);
				ASSIGN(timecycle_bloom_enabled);
				ASSIGN(timecycle_bloomintensity_scalar);
				ASSIGN(timecycle_bloomthreshold_scalar);
				ASSIGN(timecycle_bloom_night_min_clamp_enabled);
				ASSIGN(timecycle_bloom_night_min_clamp_value);

				// misc settings
				ASSIGN(discord_rpc);
				ASSIGN(limit_option_sliders);

			#undef ASSIGN
			}

			catch (const toml::syntax_error& err)
			{
				shared::common::log("CompSettings", std::format("{}", err.what()), shared::common::LOG_TYPE::LOG_TYPE_ERROR, true);
				shared::common::log("CompSettings", "Not writing defaults! Please check 'comp_settings.toml' or remove the file to re-generate it on next startup!", shared::common::LOG_TYPE::LOG_TYPE_ERROR, true);
				return false;
			}
		} else {
			shared::common::log("CompSettings", std::format("Failed to find config: {}", !is_addon_toml_file ? "rtx_comp\\comp_settings.toml" : "rtx_comp\\addon_settings\\" + addon_file_name), shared::common::LOG_TYPE::LOG_TYPE_WARN, true);
		}
#endif
		
		if (!is_addon_toml_file) {
			write_comp_settings_toml();
		}
		
		return true;
	}

	void comp_settings::load_comp_settings_only()
	{
		parse_toml();
	}

	void comp_settings::load_all_settings()
	{
		shared::common::log("CompSetting", "Reading 'rtx_comp/comp_settings.toml' ...", shared::common::LOG_TYPE::LOG_TYPE_DEFAULT, false);
		parse_toml();

#if 1
		// Process all addon comp-settings files in inverse alphabetical order (lower to higher priority)
		const auto addon_comp_settings_files = shared::utils::get_sorted_files("rtx_comp\\addon_settings", ".toml", true, false);
		for (const auto& file_name : addon_comp_settings_files)
		{
			try
			{
				shared::common::log("CompSetting", std::format("> Parsing Addon CompSetting 'rtx_comp/addon_settings/{}' ...", file_name), shared::common::LOG_TYPE::LOG_TYPE_DEFAULT, false);
				parse_toml(file_name);

			}
			catch (const toml::file_io_error& err) {
				shared::common::log("CompSetting", std::format("Failed to parse addon compsetting file '{}': {}", file_name, err.what()), shared::common::LOG_TYPE::LOG_TYPE_ERROR, true);
			}
			catch (const toml::syntax_error& err) {
				shared::common::log("CompSetting", std::format("Syntax error in addon compsetting file '{}': {}", file_name, err.what()), shared::common::LOG_TYPE::LOG_TYPE_ERROR, true);
			}
		}
#endif
	}

	comp_settings::comp_settings()
	{
		load_all_settings();

		// -----
		m_initialized = true;
		shared::common::log("CompSettings", "Module initialized.", shared::common::LOG_TYPE::LOG_TYPE_DEFAULT, false);
	}
}
